In [1]:
file.create("Hello.R")

[1] TRUE

In [2]:
print("Hello, World")

[1] "Hello, World"

In [11]:
# getting user input
name <- readline("What's your name: ")
greeting <- paste("Hello, ", name, sep="")
print(paste0(greeting)

What's your name:  paul

[1] "Hello, paul"

In [14]:
# getting user input
name <- readline("What's your name: ")
greeting <- paste0("Hello, ", name) # does not include the sep function
print(greeting)

What's your name:  paul

[1] "Hello, paul"

In [13]:
# getting user input
name <- readline("What's your name: ")
print(paste("Hello, ", name, sep=""))

What's your name:  james

[1] "Hello, james"

In [ ]:
?paste

# COUNT
file.create("filename.extension")

In [4]:
# # file.create("count.R")
# mario <- readline("Enter votes for Mario: ")
# peach <- readline("Enter votes for peach")
# bowser <- readline("Enter votes for Bowser")
# # Type Conversion in R programming language
# mario <- as.integer(mario)
# peach <- as.integer(peach) 
# bowser <- as.integer(bowser)

# total <- mario + peach + bowser

# print(paste("Total votes", total))


# file.create("count.R")
mario <- as.integer(readline("Enter votes for Mario: "))
peach <- as.integer(readline("Enter votes for peach"))
bowser <- as.integer(readline("Enter votes for Bowser"))

total <- sum(mario,peach,bowser)

print(paste("Total votes", total))

Enter votes for Mario:  100
Enter votes for peach 50
Enter votes for Bowser 200

[1] "Total votes 350"

In [ ]:
?as.integer

In [5]:
ls()

[1] "bowser" "mario"  "peach"  "total"

In [6]:
rm(list = ls())

In [13]:
# # reading files in R
# votes <- read.table("votes.csv", 
#                   sep =",", 
#                   header=TRUE)
# View(votes)

# reading files in R
votes <- read.csv("votes.csv")
View(votes)

Warning message in read.table("votes.csv", sep = ",", header = TRUE):
“incomplete final line found by readTableHeader on 'votes.csv'”

  candidate poll mail
1 Mario     37    63
2 Peach     43   107
3 Bowser    84    36

In [14]:
votes[, 3] # display the information of the 3rd column

[1]  63 107  36

In [16]:
# display specific information on a row peach's mail
votes[2,3]

[1] 107

In [17]:
votes$total <- votes$poll + votes$mail

In [20]:
write.csv(votes, "total.csv", row.names=FALSE)

In [21]:
View(read.csv("total.csv"))

  candidate poll mail total
1 Mario     37    63  100
2 Peach     43   107  150
3 Bowser    84    36  120

In [1]:
url <- "https://github.com/fivethirtyeight/data/raw/master/non-voters/nonvoters_data.csv"
voters = read.csv(url)
View(voters)

     RespId weight Q1 Q2_1 Q2_2 Q2_3 Q2_4 Q2_5 Q2_6 Q2_7 ⋯ Q30 Q31 Q32 Q33
1    470001 0.7516 1  1    1     2    4   1    4    2    ⋯ 2   NA   1  NA
2    470002 1.0267 1  1    2     2    3   1    1    2    ⋯ 3   NA  NA   1
3    470003 1.0844 1  1    1     2    2   1    1    2    ⋯ 2   NA   2  NA
4    470007 0.6817 1  1    1     1    3   1    1    1    ⋯ 2   NA   1  NA
5    480008 0.9910 1  1    1    -1    1   1    1    1    ⋯ 1   -1  NA  NA
6    480009 1.0591 1  3    2     3    4   1    3    3    ⋯ 5   NA  NA  -1
7    480010 1.1512 1  1    1     2    3   1    1    1    ⋯ 1    1  NA  NA
8    470008 1.0174 1  1    1     2    2   1    3    1    ⋯ 2   NA   1  NA
9    470010 0.8184 1  1    1     1    3   1    1    1    ⋯ 1    1  NA  NA
10   470011 1.1653 1  1    1     2    1   1    1    1    ⋯ 3   NA  NA   1
11   470013 0.9517 1  1    2     2    2   2    2    2    ⋯ 1    1  NA  NA
12   470016 1.3740 1  1    1     1    4   1    4    2    ⋯ 2   NA   1  NA
13   480020 0.8438 1  3    4     2    2   4    2    1    ⋯ 1    2  NA  NA
14   470017 1.2745 1  1    1     3    3   1    1    1    ⋯ 5   NA  NA   1
15   470018 0.9742 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
16   470019 0.9893 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
17   470022 0.8473 1  1    1     1    1   1    1    1    ⋯ 2   NA   1  NA
18   470025 1.1030 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
19   470027 0.9687 1  1    1     1    2   1    2    1    ⋯ 5   NA  NA   1
20   470028 0.8401 1  1    1     1    1   1    1    1    ⋯ 5   NA  NA   2
21   470029 1.0167 1  2    3     3    2   1    3    1    ⋯ 5   NA  NA   1
22   470030 0.9067 1  1    1     2    1   1    1    1    ⋯ 1    2  NA  NA
23   470031 0.3353 1  1    1     2    2   1    3    1    ⋯ 3   NA  NA   2
24   470033 1.1927 1  1    1     1    1   1    1    1    ⋯ 3   NA  NA   1
25   470034 1.0560 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
26   470035 0.9261 1  1    2     1    4   1    4    3    ⋯ 2   NA   1  NA
27   470036 0.9840 1  2    2     2    3   1    3    2    ⋯ 2   NA   2  NA
28   470037 1.0533 1  1    2     2    1   1    1    1    ⋯ 3   NA  NA   1
29   470038 0.7479 1  1    1    -1   -1   1    1    1    ⋯ 1    1  NA  NA
30   470039 0.9261 1  1    1     1    3   1    1    1    ⋯ 1    1  NA  NA
⋮    ⋮      ⋮      ⋮  ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋱ ⋮   ⋮   ⋮   ⋮
5807 477626 1.1907 1  3    3    2    2    2    1    2    ⋯ 3   NA  NA   1
5808 477629 0.7182 1  1    1    1    2    1    3    1    ⋯ 3   NA  NA   2
5809 477630 0.8081 1  1    2    2    3    1    1    1    ⋯ 5   NA  NA   2
5810 477631 0.8044 1  1    2    1    3    1    3    1    ⋯ 3   NA  NA   2
5811 477632 1.2926 1  1    1    2    1    2    1    1    ⋯ 1    1  NA  NA
5812 477633 1.6218 1  1    1    1    2    1    1    1    ⋯ 5   NA  NA   2
5813 477634 0.8961 1  1    2    1    2    1    2    1    ⋯ 3   NA  NA   1
5814 477635 1.3618 1  2    2    2    2    2    1    1    ⋯ 5   NA  NA   2
5815 477637 0.9726 1  1    1    2    2    1    1    1    ⋯ 1    2  NA  NA
5816 477638 1.0894 1  1    1    2    1    1    2    1    ⋯ 3   NA  NA   1
5817 477639 1.1379 1  1    2    2    1    1    1    1    ⋯ 1    1  NA  NA
5818 477640 2.0268 1  3    2    2    2    3    1    2    ⋯ 1    2  NA  NA
5819 477644 0.8133 1  1    4    3    4    1    2    2    ⋯ 2   NA   2  NA
5820 477646 0.8741 1  1    2    1    1    1    1    1    ⋯ 2   NA   2  NA
5821 477647 1.1846 1  1    1    1    3    1    1    1    ⋯ 3   NA  NA   2
5822 477648 1.2745 1  1    1    1    2    1    1    1    ⋯ 1    1  NA  NA
5823 477649 1.1198 1  1    2    2    1    1    1    1    ⋯ 1    1  NA  NA
5824 477650 0.7646 1  1    2    1    3    2    3    2    ⋯ 3   NA  NA   1
5825 477651 1.0111 1  4    3    4    4    4    4    4    ⋯ 5   NA  NA   2
5826 477653 0.8688 1  2    3    1    4    1    4    3    ⋯ 3   NA  NA   2
5827 477654 0.7655 1  1    1    1    2    1    1    1    ⋯ 3   NA  NA   2
5828 477657 1.5600 1  1    1    1    1    1    1    1    ⋯ 1    1  NA  NA
5829 477658 1.3218 1  1    1    2    4    2    4    2    ⋯ 4   NA  NA   1
5830 477660 1.2671 1  2    1    2    1    1    2    1    ⋯ 2   NA   2  NA
5831 477661 1.2518 1  1    2    1    2    2    1    1    ⋯ 5   NA  NA   2
5832 477662 1.1916 1  1    3    1    3    1    2    2    ⋯ 2   NA   1  NA
5833 477663 1.4623 1  1    1    1    2    1    2    1    ⋯ 2   NA   2  NA
5834 488322 0.9252 1  1    2    1    3    1    1    2    ⋯ 2   NA   1  NA
5835 488325 2.6311 1  2    2    2    2    2    2    2    ⋯ 3   NA  NA   1
5836 477666 1.6218 1  1    3    2    3    1    1    2    ⋯ 5   NA  NA   2
     ppage educ                race        gender income_cat     voter_category
1    73    College             White       Female $75-125k       always
2    90    College             White       Female $125k or more  always
3    53    College             White       Male   $125k or more  sporadic
4    58    Some college        Black       Female $40-75k        sporadic
5    81    High school or less White       Male   $40-75k        always
6    61    High school or less White       Female $40-75k        rarely/never
7    80    High school or less White       Female $125k or more  always
8    68    Some college        Other/Mixed Female $75-125k       always
9    70    College             White       Male   $125k or more  always
10   83    Some college        White       Male   $125k or more  always
11   43    College             White       Male   $75-125k       sporadic
12   42    College             White       Female $125k or more  sporadic
13   48    College             White       Male   $40-75k        rarely/never
14   52    Some college        White       Male   $125k or more  sporadic
15   80    High school or less White       Female $40-75k        always
16   76    High school or less White       Female $75-125k       sporadic
17   73    Some college        White       Female Less than $40k always
18   52    College             White       Female $125k or more  always
19   63    Some college        White       Male   $75-125k       always
20   81    Some college        White       Male   Less than $40k always
21   46    Some college        Other/Mixed Male   Less than $40k rarely/never
22   62    Some college        White       Male   $40-75k        always
23   62    College             Black       Male   $75-125k       sporadic
24   84    High school or less White       Male   Less than $40k sporadic
25   53    College             White       Female $75-125k       sporadic
26   71    High school or less White       Female Less than $40k always
27   50    High school or less Black       Female Less than $40k rarely/never
28   77    Some college        White       Female $75-125k       sporadic
29   67    College             White       Male   $40-75k        always
30   80    High school or less White       Female Less than $40k always
⋮    ⋮     ⋮                   ⋮           ⋮      ⋮              ⋮
5807 36    High school or less White       Male   $75-125k       rarely/never
5808 28    College             Hispanic    Male   $75-125k       sporadic
5809 54    Some college        Hispanic    Female $125k or more  sporadic
5810 73    College             White       Male   $125k or more  sporadic
5811 23    Some college        White       Female $40-75k        always
5812 26    High school or less Black       Female Less than $40k rarely/never
5813 61    High school or less White       Male   Less than $40k sporadic
5814 39    High school or less White       Female Less than $40k sporadic
5815 40    College             Other/Mixed Male   $125k or more  sporadic
5816 41    Some college        White       Male   $75-125k       sporadic
5817 44    Some college        White       Male   $75-125k       rarely/never
5818 34    High school or less White       Male   Less than $40k rarely/never
5819 29    College             Hispanic    Male   $40-75k        sporadic
5820 70    Some college        White       Male   $75-125k       always
5821 32    Some college        Other/Mixed Female $40-75k        sporadic
5822 55    Some college        White       Male   $125k or more  sporadic
5823 56    Some college        White       Female $75-125k       sporadic
5824 36    Some college        Hispanic    Female $40-75k        rarely/never
5825 59    High school or less Hispanic    Male   $75-125k       sporadic
5826 23    College             White       Female Less than $40k rarely/never
5827 47    High school or less Hispanic    Male   $40-75k        sporadic
5828 45    Some college        White       Female $125k or more  sporadic
5829 37    Some college        White       Female $40-75k        sporadic
5830 33    High school or less Black       Female Less than $40k rarely/never
5831 26    High school or less White       Female $75-125k       rarely/never
5832 27    Some college        Hispanic    Male   $40-75k        always
5833 59    High school or less White       Female $125k or more  rarely/never
5834 51    College             Other/Mixed Male   $125k or more  sporadic
5835 22    High school or less Black       Female Less than $40k always
5836 22    High school or less Black       Female Less than $40k always

In [5]:
factor(voters$Q21, labels = c("Yes", "No", "Unsure/Undecided"), exclude = c(-1))

   [1] Yes              Yes              Yes              Yes
   [5] Yes              No               Yes              Yes
   [9] Yes              No               Yes              Yes
  [13] No               Yes              Unsure/Undecided Yes
  [17] Yes              Yes              Yes              Yes
  [21] No               Yes              Yes              Yes
  [25] Yes              Yes              No               Yes
  [29] Yes              Yes              Yes              Yes
  [33] Yes              Yes              Yes              Yes
  [37] Yes              Yes              Yes              Yes
  [41] Unsure/Undecided Yes              Yes              Yes
  [45] Yes              Yes              Yes              No
  [49] Yes              Yes              Yes              Yes
  [53] Yes              Yes              Yes              Yes
  [57] Yes              Yes              Yes              Yes
  [61] Yes              Yes              No               Yes
  [65] Yes              Yes              No               Unsure/Undecided
  [69] Yes              Yes              Yes              Yes
  [73] Yes              Yes              Unsure/Undecided Unsure/Undecided
  [77] Yes              Yes              Unsure/Undecided Yes
  [81] Yes              Yes              Yes              Yes
  [85] Yes              Yes              No               Yes
  [89] Yes              Yes              Yes              Yes
  [93] Yes              Yes              Yes              Yes
  [97] No               Yes              Unsure/Undecided Yes
 [101] Yes              No               No               Unsure/Undecided
 [105] Yes              Yes              Yes              Yes
 [109] Yes              Yes              Yes              Yes
 [113] Yes              Yes              Yes              Yes
 [117] Yes              Yes              Yes              Yes
 [121] Yes              Yes              Yes              Yes
 [125] Yes              Yes              Yes              Yes
 [129] Yes              Unsure/Undecided Yes              Yes
 [133] Yes              No               Unsure/Undecided Unsure/Undecided
 [137] Yes              Yes              Yes              Yes
 [141] Yes              Yes              Yes              No
 [145] Yes              Yes              Yes              Yes
 [149] Yes              Yes              Yes              Yes
 [153] Yes              Yes              Yes              Unsure/Undecided
 [157] Yes              Yes              Yes              Yes
 [161] Yes              Yes              Yes              No
 [165] Yes              Yes              Yes              Yes
 [169] Yes              Yes              Yes              No
 [173] Yes              Yes              No               No
 [177] Yes              Unsure/Undecided Yes              Yes
 [181] Unsure/Undecided Yes              Yes              Yes
 [185] Yes              Yes              Yes              Yes
 [189] Yes              Yes              Yes              Yes
 [193] Yes              Yes              Yes              Yes
 [197] Yes              Yes              Yes              Yes
 [201] No               Yes              Yes              Yes
 [205] Yes              Yes              Yes              Unsure/Undecided
 [209] Unsure/Undecided No               Yes              Yes
 [213] Yes              Yes              Yes              Yes
 [217] Yes              Yes              Yes              Yes
 [221] Yes              Yes              Yes              Yes
 [225] Yes              Yes              Yes              Yes
 [229] Yes              Yes              Yes              Yes
 [233] Yes              Yes              Yes              Yes
 [237] Yes              Unsure/Undecided Yes              Yes
 [241] Yes              Unsure/Undecided Yes              Yes
 [245] Yes              Yes              Yes              Yes
 [249] Yes              Yes              Yes              Yes
 [253] Yes              Yes              Yes              Yes
 [257] Yes              Unsure/Undecided Yes              Yes
 [261] Yes              Yes              Yes              Yes
 [265] Yes              Yes              Yes              Yes
 [269] Yes              Yes              Yes              Unsure/Undecided
 [273] Yes              Yes              Yes              <NA>
 [277] Unsure/Undecided Yes              Yes              Yes
 [281] Yes              Yes              Yes              Yes
 [285] Yes              Yes              Yes              No
 [289] Yes              Yes              Yes              Yes
 [293] Yes              Yes              Yes              Yes
 [297] Yes              Yes              Yes              No
 [301] Yes              Yes              Yes              Yes
 [305] Yes              Yes              No               Yes
 [309] Yes              Yes              Yes              Yes
 [313] Yes              Yes              Yes              Yes
 [317] Yes              Yes              Yes              Yes
 [321] Yes              No               Yes              Yes
 [325] Yes              Unsure/Undecided Yes              Yes
 [329] Unsure/Undecided Yes              Yes              Yes
 [333] Yes              Yes              Yes              Yes
 [337] Yes              Yes              Yes              No
 [341] Yes              Yes              Yes              Yes
 [345] Yes              Yes              Yes              Yes
 [349] Yes              Yes              Yes              Yes
 [353] Yes              Yes              Yes              Yes
 [357] Yes              Unsure/Undecided Yes              Yes
 [361] Yes              Yes              Yes              Yes
 [365] Yes              Yes              Yes              Yes
 [369] Yes              Yes              Yes              Yes
 [373] No               Yes              Yes              Yes
 [377] Yes              Yes              No               Yes
 [381] Yes              Yes              Yes              Yes
 [385] Yes              No               Yes              Yes
 [389] Yes              Yes              Yes              Yes
 [393] Yes              Yes              Yes              Yes
 [397] No               Yes              Yes              Yes
 [401] Yes              Yes              Yes              Yes
 [405] Yes              Yes              Yes              Yes
 [409] Yes              Yes              Unsure/Undecided Yes
 [413] Yes              Yes              Yes              No
 [417] Yes              Yes              Yes              Yes
 [421] Yes              No               Yes              Yes
 [425] No               Yes              Yes              Yes
 [429] Yes              Yes              Yes              Yes
 [433] Yes              Yes              Yes              Yes
 [437] Yes              Yes              Yes              Yes
 [441] Yes              Yes              Yes              Yes
 [445] No               Yes              Yes              Yes
 [449] Yes              Yes              Yes              Yes
 [453] Yes              Unsure/Undecided Yes              Yes
 [457] Yes              Yes              Yes              Yes
 [461] Yes              Yes              Yes              Yes
 [465] Yes              Yes              Yes              Unsure/Undecided
 [469] Yes              Yes              Yes              Yes
 [473] Yes              Yes              Yes              Yes
 [477] Yes              Yes              Yes              Yes
 [481] No               Yes              Yes              Yes
 [485] Yes              Yes              Yes              Yes
 [489] Unsure/Undecided Yes              Yes              Yes
 [493] Yes              Yes              Yes              Yes
 [497] Yes              Yes              Yes              Yes
 [501] Yes              Yes              Yes              Yes
 [505] Yes              Unsure/Undecided Yes              Yes
 [509] Yes              Yes              Yes              Yes
 [513] Yes              Yes              Unsure/Undecided Yes
 [517] <NA>             Yes              Yes              Yes
 [521] Yes              Yes              Yes              Yes
 [525] Yes              Yes              Yes              Yes
 [529] Yes              Yes              Yes              Yes
 [533] Yes              Yes              Yes              Yes
 [537] Yes              Yes              Yes              Yes
 [541] Yes              Yes              Yes              Yes
 [545] Yes              Yes              Yes              Yes
 [549] Yes              Yes              Yes              Yes
 [553] Yes              Yes              Yes              Yes
 [557] Yes              Yes              Yes              Yes
 [561] Yes              Yes              Yes              Yes
 [565] Unsure/Undecided Yes              Yes              Yes
 [569] Yes              Yes              Yes              Yes
 [573] Yes              Yes              Yes              Yes
 [577] Yes              Yes              Yes              Yes
 [581] Yes              Yes              Yes              Yes
 [585] <NA>             Yes              Yes              Yes
 [589] Yes              Yes              Unsure/Undecided Yes
 [593] Yes              Yes              Yes              Yes
 [597] Yes              Yes              Yes              Yes
 [601] Yes              Yes              Yes              Yes
 [605] Yes              Yes              Yes              Yes
 [609] Yes              Yes              Yes              Yes
 [613] Yes              Yes              Yes              Yes
 [617] Yes              No               Yes              Yes
 [621] Yes              Yes              Yes              Yes
 [625] Yes              Yes              Yes              Yes
 [629] Unsure/Undecided Yes              Yes              No
 [633] Yes              Yes              Yes              Yes
 [637] Yes              Yes              Yes              Yes
 [641] Yes              Yes              Yes              Yes
 [645] Yes              Yes              Yes              Yes
 [649] Unsure/Undecided Yes              Yes              Yes
 [653] Yes              Yes              Yes              Yes
 [657] Yes              Yes              Yes              Yes
 [661] Yes              Unsure/Undecided Yes              Yes
 [665] Yes              Yes              Yes              Yes
 [669] Yes              Unsure/Undecided Yes              Yes
 [673] Yes              Yes              Yes              Yes
 [677] Yes              Yes              Yes              Yes
 [681] Yes              Yes              Yes              Yes
 [685] Yes              Yes              Yes              Yes
 [689] Yes              Yes              Yes              Yes
 [693] Yes              Yes              Yes              Yes
 [697] Yes              No               Yes              Yes
 [701] Yes              Yes              Yes              Yes
 [705] Yes              Yes              Yes              Yes
 [709] Yes              Yes              No               Yes
 [713] Yes              Yes              Yes              Yes
 [717] Yes              Yes              Yes              Yes
 [721] Yes              Yes              Yes              Yes
 [725] Yes              Yes              Yes              Yes
 [729] Yes              Yes              Yes              Unsure/Undecided
 [733] Yes              Yes              Yes              Yes
 [737] Yes              Yes              Yes              Yes
 [741] Yes              Yes              Yes              Yes
 [745] Yes              Yes              Yes              Yes
 [749] Yes              No               Unsure/Undecided Yes
 [753] Yes              Yes              Yes              Yes
 [757] Yes              Unsure/Undecided Yes              Yes
 [761] Yes              Yes              Yes              Yes
 [765] Yes              Yes              Unsure/Undecided Unsure/Undecided
 [769] No               Yes              Yes              Yes
 [773] Yes              Yes              Yes              Yes
 [777] Yes              No               Yes              Yes
 [781] Yes              Yes              Yes              Yes
 [785] Yes              Yes              Yes              Yes
 [789] Unsure/Undecided Yes              Yes              Yes
 [793] Yes              Yes              Yes              Yes
 [797] Yes              Yes              Yes              Yes
 [801] Yes              Yes              Yes              Yes
 [805] Yes              Yes              Yes              Yes
 [809] Yes              Yes              Yes              Yes
 [813] No               Yes              Yes              Yes
 [817] Yes              Yes              Yes              Yes
 [821] Yes              Yes              Yes              Yes
 [825] No               Yes              Yes              Yes
 [829] Yes              No               Yes              Yes
 [833] Yes              Yes              Yes              Yes
 [837] Yes              Yes              Yes              Yes
 [841] Yes              Yes              Yes              Yes
 [845] Yes              Yes              Yes              Yes
 [849] Yes              Yes              Yes              Yes
 [853] Yes              Yes              Yes              Yes
 [857] Yes              Yes              Yes              Yes
 [861] Yes              Yes              Yes              Yes
 [865] Yes              Yes              Yes              Yes
 [869] Yes              Yes              Yes              Yes
 [873] Yes              Yes              Yes              Yes
 [877] Yes              Yes              Yes              Yes
 [881] Yes              Yes              Yes              Yes
 [885] Yes              No               Yes              Yes
 [889] Yes              No               Yes              Yes
 [893] Yes              Yes              Yes              Yes
 [897] Yes              Yes              Yes              Yes
 [901] Yes              Yes              Yes              Unsure/Undecided
 [905] Yes              Yes              Yes              Yes
 [909] Yes              Yes              Yes              Yes
 [913] Yes              Yes              Yes              Yes
 [917] Yes              Yes              Yes              Yes
 [921] Yes              Yes              Yes              Yes
 [925] Yes              Yes              Yes              Yes
 [929] Yes              Yes              Yes              Unsure/Undecided
 [933] Yes              Yes              Yes              Yes
 [937] Yes              Yes              Yes              Yes
 [941] Yes              Yes              Yes              Yes
 [945] Yes              Yes              No               Yes
 [949] Yes              Yes              Yes              Yes
 [953] Yes              Yes              Yes              Yes
 [957] Yes              Yes              Yes              Yes
 [961] Yes              Yes              Yes              Yes
 [965] Yes              Yes              Yes              Yes
 [969] Yes              Yes              Yes              No
 [973] Yes              Yes              Yes              Yes
 [977] Yes              Yes              Yes              Yes
 [981] Yes              Yes              Yes              Yes
 [985] Yes              Yes              Yes              Yes
 [989] Yes              Yes              Yes              Yes
 [993] Yes              Yes              Unsure/Undecided Yes
 [997] Yes              Yes              Yes              Yes
[1001] Yes              Yes              Yes              Yes
[1005] Unsure/Undecided Yes              Yes              Yes
[1009] Yes              Yes              Yes              No
[1013] Yes              Yes              Yes              Yes
[1017] Yes              Yes              Yes              Yes
[1021] Yes              Yes              No               Yes
[1025] Yes              Yes              Yes              Yes
[1029] Yes              No               Yes              Yes
[1033] Yes              Yes              Yes              Yes
[1037] Yes              Yes              Yes              Yes
[1041] No               Yes              Yes              Yes
[1045] Yes              Yes              No               Yes
[1049] No               No               Yes              Yes
[1053] Yes              Unsure/Undecided Unsure/Undecided Yes
[1057] Yes              Yes              Yes              <NA>
[1061] Yes              Yes              Yes              Yes
[1065] Yes              No               Yes              Yes
[1069] No               Yes              <NA>             Yes
[1073] Yes              Unsure/Undecided Yes              Yes
[1077] Yes              Yes              No               Yes
[1081] Yes              Yes              Unsure/Undecided Yes
[1085] Yes              Yes              Yes              Yes
[1089] No               Yes              No               Yes
[1093] Yes              Yes              Yes              Yes
[1097] Yes              Yes              Yes              Unsure/Undecided
[1101] Yes              Yes              Yes              Yes
[1105] Yes              Yes              Yes              Yes
[1109] Yes              No               No               Yes
[1113] Yes              Yes              Yes              Yes
[1117] Yes              Yes              Yes              Unsure/Undecided
[1121] Yes              Yes              Yes              Yes
[1125] Yes              Yes              Yes              Yes
[1129] Yes              Yes              Yes              Yes
[1133] Yes              Yes              Yes              Yes
[1137] Yes              Yes              Yes              No
[1141] Yes              Yes              Yes              Yes
[1145] Unsure/Undecided No               Yes              Unsure/Undecided
[1149] Unsure/Undecided Yes              Yes              Yes
[1153] Yes              Unsure/Undecided Yes              Yes
[1157] Yes              Yes              Yes              Yes
[1161] Yes              Unsure/Undecided Yes              <NA>
[1165] Yes              Unsure/Undecided Unsure/Undecided Yes
[1169] Yes              Yes              No               Yes
[1173] Unsure/Undecided Yes              Yes              No
[1177] Yes              Unsure/Undecided Yes              Unsure/Undecided
[1181] Yes              Yes              Yes              Yes
[1185] Yes              Yes              Unsure/Undecided Yes
[1189] Yes              Yes              Yes              Yes
[1193] Yes              Yes              Yes              Yes
[1197] Yes              Yes              Yes              Yes
[1201] Yes              Yes              Yes              Yes
[1205] Yes              Yes              No               No
[1209] Yes              No               No               No
[1213] Yes              Yes              Yes              Yes
[1217] Yes              Yes              Yes              Yes
[1221] Yes              Yes              Yes              Yes
[1225] Yes              Yes              Yes              Yes
[1229] Yes              Yes              Yes              No
[1233] Yes              Yes              Yes              Yes
[1237] Yes              Unsure/Undecided Yes              Unsure/Undecided
[1241] Yes              Yes              Yes              Yes
[1245] No               Yes              Yes              Yes
[1249] Yes              Yes              Yes              Unsure/Undecided
[1253] Yes              Yes              Yes              Yes
[1257] Yes              Yes              Yes              Yes
[1261] Yes              Yes              Yes              Yes
[1265] Yes              Yes              Yes              Yes
[1269] Yes              Yes              No               Yes
[1273] Yes              No               Yes              Yes

In [6]:
?factor

factor                  package:base                   R Documentation

_F_a_c_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     The function ‘factor’ is used to encode a vector as a factor (the
     terms ‘category’ and ‘enumerated type’ are also used for factors).
     If argument ‘ordered’ is ‘TRUE’, the factor levels are assumed to
     be ordered.  For compatibility with S there is also a function
     ‘ordered’.

     ‘is.factor’, ‘is.ordered’, ‘as.factor’ and ‘as.ordered’ are the
     membership and coercion functions for these classes.

_U_s_a_g_e:

     factor(x = character(), levels, labels = levels,
            exclude = NA, ordered = is.ordered(x), nmax = NA)

     ordered(x = character(), ...)

     is.factor(x)
     is.ordered(x)

     as.factor(x)
     as.ordered(x)

     addNA(x, ifany = FALSE)

     .valid.factor(object)

_A_r_g_u_m_e_n_t_s:

       x: a vector of data, usually taking a small number of distinct
          values.

  levels: an optional vector of the unique values (as character
          strings) that ‘x’ might have taken.  The default is the
          unique set of values taken by ‘as.character(x)’, sorted into
          increasing order _of ‘x’_.  Note that this set can be
          specified as smaller than ‘sort(unique(x))’.

  labels: _either_ an optional character vector of labels for the
          levels (in the same order as ‘levels’ after removing those in
          ‘exclude’), _or_ a character string of length 1.  Duplicated
          values in ‘labels’ can be used to map different values of ‘x’
          to the same factor level.

 exclude: a vector of values to be excluded when forming the set of
          levels.  This may be factor with the same level set as ‘x’ or
          should be a ‘character’.

 ordered: logical flag to determine if the levels should be regarded as
          ordered (in the order given).

    nmax: an upper bound on the number of levels; see ‘Details’.

     ...: (in ‘ordered(.)’): any of the above, apart from ‘ordered’
          itself.

   ifany: only add an ‘NA’ level if it is used, i.e.  if
          ‘any(is.na(x))’.

  object: an R object.

_D_e_t_a_i_l_s:

     The type of the vector ‘x’ is not restricted; it only must have an
     ‘as.character’ method and be sortable (by ‘order’).

     Ordered factors differ from factors only in their class, but
     methods and model-fitting functions may treat the two classes
     quite differently, see ‘options("contrasts")’.

     The encoding of the vector happens as follows.  First all the
     values in ‘exclude’ are removed from ‘levels’. If ‘x[i]’ equals
     ‘levels[j]’, then the ‘i’-th element of the result is ‘j’.  If no
     match is found for ‘x[i]’ in ‘levels’ (which will happen for
     excluded values) then the ‘i’-th element of the result is set to
     ‘NA’.

     Normally the ‘levels’ used as an attribute of the result are the
     reduced set of levels after removing those in ‘exclude’, but this
     can be altered by supplying ‘labels’.  This should either be a set
     of new labels for the levels, or a character string, in which case
     the levels are that character string with a sequence number
     appended.

     ‘factor(x, exclude = NULL)’ applied to a factor without ‘NA’s is a
     no-operation unless there are unused levels: in that case, a
     factor with the reduced level set is returned.  If ‘exclude’ is
     used, since R version 3.4.0, excluding non-existing character
     levels is equivalent to excluding nothing, and when ‘exclude’ is a
     ‘character’ vector, that _is_ applied to the levels of ‘x’.
     Alternatively, ‘exclude’ can be factor with the same level set as
     ‘x’ and will exclude the levels present in ‘exclude’.

     The codes of a factor may contain ‘NA’.  For a numeric ‘x’, set
     ‘exclude = NULL’ to make ‘NA’ an extra level (prints as ‘<NA>’);
     by default, this is the last level.

     If ‘NA’ is a level, the way to set a code to be missing (as
     opposed to the code of the missing level) is to use ‘is.na’ on the
     left-hand-side of an assignment (as in ‘is.na(f)[i] <- TRUE’;
     indexing inside ‘is.na’ does not work).  Under those circumstances
     missing values are currently printed as ‘<NA>’, i.e., identical to
     entries of level ‘NA’.

     ‘is.factor’ is generic: you can write methods to handle specific
     classes of objects, see InternalMethods.

     Where ‘levels’ is not supplied, ‘unique’ is called.  Since factors
     typically have quite a small number of levels, for large vectors
     ‘x’ it is helpful to supply ‘nmax’ as an upper bound on the number
     of unique values.

     When using ‘c’ to combine a (possibly ordered) factor with other
     objects, if all objects are (possibly ordered) factors, the result
     will be a factor with levels the union of the level sets of the
     elements, in the order the levels occur in the level sets of the
     elements (which means that if all the elements have the same level
     set, that is the level set of the result), equivalent to how
     ‘unlist’ operates on a list of factor objects.

_V_a_l_u_e:

     ‘factor’ returns an object of class ‘"factor"’ which has a set of
     integer codes the length of ‘x’ with a ‘"levels"’ attribute of
     mode ‘character’ and unique (‘!anyDuplicated(.)’) entries.  If
     argument ‘ordered’ is true (or ‘ordered()’ is used) the result has
     class ‘c("ordered", "factor")’.  Undocumentedly for a long time,
     ‘factor(x)’ loses all ‘attributes(x)’ but ‘"names"’, and resets
     ‘"levels"’ and ‘"class"’.

     Applying ‘factor’ to an ordered or unordered factor returns a
     factor (of the same type) with just the levels which occur: see
     also ‘[.factor’ for a more transparent way to achieve this.

     ‘is.factor’ returns ‘TRUE’ or ‘FALSE’ depending on whether its
     argument is of type factor or not.  Correspondingly, ‘is.ordered’
     returns ‘TRUE’ when its argument is an ordered factor and ‘FALSE’
     otherwise.

     ‘as.factor’ coerces its argument to a factor.  It is an
     abbreviated (sometimes faster) form of ‘factor’.

     ‘as.ordered(x)’ returns ‘x’ if this is ordered, and ‘ordered(x)’
     otherwise.

     ‘addNA’ modifies a factor by turning ‘NA’ into an extra level (so
     that ‘NA’ values are counted in tables, for instance).

     ‘.valid.factor(object)’ checks the validity of a factor, currently
     only ‘levels(object)’, and returns ‘TRUE’ if it is valid,
     otherwise a string describing the validity problem.  This function
     is used for ‘validObject(<factor>)’.

_W_a_r_n_i_n_g:

     The interpretation of a factor depends on both the codes and the
     ‘"levels"’ attribute.  Be careful only to compare factors with the
     same set of levels (in the same order).  In particular,
     ‘as.numeric’ applied to a factor is meaningless, and may happen by
     implicit coercion.  To transform a factor ‘f’ to approximately its
     original numeric values, ‘as.numeric(levels(f))[f]’ is recommended
     and slightly more efficient than ‘as.numeric(as.character(f))’.

     The levels of a factor are by default sorted, but the sort order
     may well depend on the locale at the time of creation, and should
     not be assumed to be ASCII.

     There are some anomalies associated with factors that have ‘NA’ as
     a level.  It is suggested to use them sparingly, e.g., only for
     tabulation purposes.

_C_o_m_p_a_r_i_s_o_n _o_p_e_r_a_t_o_r_s _a_n_d _g_r_o_u_p _g_e_n_e_r_i_c _m_e_t_h_o_d_s:

     There are ‘"factor"’ and ‘"ordered"’ methods for the group generic
     ‘Ops’ which provide methods for the Comparison operators, and for
     the ‘min’, ‘max’, and ‘range’ generics in ‘Summary’ of
     ‘"ordered"’.  (The rest of the groups and the ‘Math’ group
     generate an error as they are not meaningful for factors.)

     Only ‘==’ and ‘!=’ can be used for factors: a factor can only be
     compared to another factor with an identical set of levels (not
     necessarily in the same ordering) or to a character vector.
     Ordered factors are compared in the same way, but the general
     dispatch mechanism precludes comparing ordered and unordered
     factors.

     All the comparison operators are available for ordered factors.
     Collation is done by the levels of the operands: if both operands
     are ordered factors they must have the same level set.

_N_o_t_e:

     In earlier versions of R, storing character data as a factor was
     more space efficient if there is even a small proportion of
     repeats.  However, identical character strings now share storage,
     so the difference is small in most cases.  (Integer values are
     stored in 4 bytes whereas each reference to a character string
     needs a pointer of 4 or 8 bytes.)

_R_e_f_e_r_e_n_c_e_s:

     Chambers, J. M. and Hastie, T. J. (1992) _Statistical Models in
     S_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘[.factor’ for subsetting of factors.

     ‘gl’ for construction of balanced factors and ‘C’ for factors with
     specified contrasts.  ‘levels’ and ‘nlevels’ for accessing the
     levels, and ‘unclass’ to get integer codes.

_E_x_a_m_p_l_e_s:

     (ff <- factor(substring("statistics", 1:10, 1:10), levels = letters))
     as.integer(ff)      # the internal codes
     (f. <- factor(ff))  # drops the levels that do not occur
     ff[, drop = TRUE]   # the same, more transparently

     factor(letters[1:20], labels = "letter")

     class(ordered(4:1)) # "ordered", inheriting from "factor"
     z <- factor(LETTERS[3:1], ordered = TRUE)
     ## and "relational" methods work:
     stopifnot(sort(z)[c(1,3)] == range(z), min(z) < max(z))


     ## suppose you want "NA" as a level, and to allow missing values.
     (x <- factor(c(1, 2, NA), exclude = NULL))
     is.na(x)[2] <- TRUE
     x  # [1] 1    <NA> <NA>
     is.na(x)
     # [1] FALSE  TRUE FALSE

     ## More rational, since R 3.4.0 :
     factor(c(1:2, NA), exclude =  "" ) # keeps <NA> , as
     factor(c(1:2, NA), exclude = NULL) # always did
     ## exclude = <character>
     z # ordered levels 'A < B < C'
     factor(z, exclude = "C") # does exclude
     factor(z, exclude = "B") # ditto

     ## Now, labels maybe duplicated:
     ## factor() with duplicated labels allowing to "merge levels"
     x <- c("Man", "Male", "Man", "Lady", "Female")
     ## Map from 4 different values to only two levels:
     (xf <- factor(x, levels = c("Male", "Man" , "Lady",   "Female"),
                      labels = c("Male", "Male", "Female", "Female")))
     #> [1] Male   Male   Male   Female Female
     #> Levels: Male Female

     ## Using addNA()
     Month <- airquality$Month
     table(addNA(Month))
     table(addNA(Month, ifany = TRUE))

In [8]:
load("temps.RData")

Warning message in readChar(con, 5L, useBytes = TRUE):
“cannot open compressed file 'temps.RData', probable reason 'No such file or directory'”

ERROR: Error in readChar(con, 5L, useBytes = TRUE): cannot open the connection